name: analyze-failed-checks.yml
on:
  workflow_run:
    workflows: ["Test that always fails"]
    types: [completed]

jobs:
  junie:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Junie
        id: junie
        uses: Megamgistr/gh-action@main
        with:
          junie_api_key: ${{ secrets.JUNIE_API_KEY }}
          allowed_mcp_servers: mcp_github_checks_server
          prompt: |
            The user makes changes and this makes a CI checks in Pull Request fails.
            You need to investigate the checks failures and suggest a fix.
            
            You have connected MCP with get_pr_failed_checks_info controller. Call it to get the failed checks logs info.
