name: analyze-failed-checks.yml
on:
  pull_request:
    types: [synchronize, opened]

jobs:
  junie:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Junie
        id: junie
        uses: Megamgistr/gh-action@main
        with:
          junie_api_key: ${{ secrets.JUNIE_API_KEY }}
          resolve_conflicts: true